language: node_js
sudo: false
node_js:
- '8'
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: sebastian.nicolas.meilan@gmail.com
  api_key:
    secure: lip/1kWXl+pHO+uyC6Lcb9UkQRuL5aiIbEybpZA7cdnjIq4yOTfrQcbCWQtwGLWCzb6Z78kJvwxHUOeXdjl2b3WC4slk1T7AErw0jbJs7GOC61yKA84CAn38r8VlbfCqWfZB7e4VjISu9QvpXpCJtxWsEiepJnKtZ4al1/WbKUADuknDWzipxMyZbVTmy9GacMiykUJS4ijoUKR541DtrvPE8Lmp6MAl7IKQP58jnrYaGiSQUfNGfj/64uuxIOB8epHJ+/q0EsIX54h5E3lovlOo/i4nTX/UHOJnA+Rl4jT8HtJ40xgVHIQaOL6fTIlBj1CImSth/ulqELdBzumQhJTj9lGrKKrsrnyJQqq1fKA6yvF9MrN2d6PbqFwlW3Oer8UmJuHyyVXXvwygnW/rF+w3LVuKf3wIVTpXWW3FxQ/prGcnzL5i9T+in3VPf+2YKAPEXidQY0bdYWCTiMJlMMKjS9YAI0vKMlB8OvObbhi5m4RnMCoLCscTlTCsOhxXxg80UahYL95F/TvsoBWuaOK/00ARPjcE1JZopOTJ5mWpmkO8+2KI2n3bh+IZydVOnt6K/Tpj68Nal40Htk7OapdljYOEiDQBY6pn29Tb/J1apSn6WPcO98qV2sDB3KAKkSZHrsobfQLSSrxd6an2FmKcw8O/W3+NYepzfdlTLfg=
  tags: true
  skip_cleanup: true
  on:
    branch: master
